### ISSUE TITLE
Parser should error on unmatched closing paren/brace

### ISSUE THREAD

**Issue by ikappaki** [clojure-emacs/parseclj#25]
e.g. I would have expected the following example with an unmatched closing brace
```
(require 'parseclj)
(cl-prettyprint (parseclj-parse-clojure "{:a 1}}"))
```

to give an error such as "At position 7, unmatched :rbrace", 

but it returns an emtpy AST

```
((:node-type . :root)
 (:position . 1)
 (:children ((:node-type) (:position) (:children))))
```

**Comment by plexus** [comment]
Hey, I just copied your snippet and the error you're suggesting is exactly what I'm seeing:

![2021-09-27_170647_Emacs](https://user-images.githubusercontent.com/32212/134935259-52c0b2e3-292a-4aa4-b274-88102c50b205.png)

So it would appear this is no longer an issue.

**Comment by ikappaki** [comment]
(Yes, sorry, I forgot to link it to the #24 PR which fixed it :))

**Comment by plexus** [comment]
Ah yes, great :)
