### ISSUE TITLE
Dependency a.el still required

### ISSUE THREAD

**Issue by sebastianpoeplau** [clojure-emacs/parseclj#30]
First of all, thanks for making this package!

The recent commit 089160a4873fe64cd0b3ffcbecbe7ebd0633014b has dropped a.el from the list of declared dependencies, but the code [still requires it](https://github.com/clojure-emacs/parseclj/blob/507720a6322078e9f0325b7fb2d5afd862e02f28/parseclj-ast.el#L30). I can't tell for sure whether the `require` is actually needed or just a leftover from before the inlining - dropping it from parseclj-ast.el and parseclj-parser.el doesn't cause errors for me.

**Comment by sebastianpoeplau** [comment]
Actually, the tests fail without the `require` because there is still a reference to `a-list`.

https://github.com/clojure-emacs/parseclj/blob/507720a6322078e9f0325b7fb2d5afd862e02f28/parseclj-lex.el#L77

**Comment by andreyorst** [comment]
Just updated, and got bitten by that, as `cider-jack-in-clj` stopped working. Navigating stacktrace and removing the require from `parseclj-parer.el` made it work again, but I'm unsure if anything else broke with this change

https://github.com/clojure-emacs/parseclj/blob/507720a6322078e9f0325b7fb2d5afd862e02f28/parseclj-parser.el#L35

**Comment by plexus** [comment]
Thanks for spotting that @sebastianpoeplau and @andreyorst . `a.el` is still a dependency for the tests, but it should be possible to use the library without it now. I released a fix, please let me know if that helps.

**Comment by andreyorst** [comment]
@plexus pulling the latest `1.0.1` and running `cider-jack-in-clj` still errors:

```
Debugger entered--Lisp error: (file-missing "Cannot open load file" "No such file or directory" "a")
  require(a)
  load-with-code-conversion("/home/alist/.config/emacs/straight/build-28.0.50/parseclj/parseclj-parser.el" "/home/alist/.config/emacs/straight/build-28.0.50/parseclj/parseclj-parser.el" nil t)
  require(parseclj-parser)
  load-with-code-conversion("/home/alist/.config/emacs/straight/build-28.0.50/parseedn/parseedn.el" "/home/alist/.config/emacs/straight/build-28.0.50/parseedn/parseedn.el" nil t)
  require(parseedn)
  load-with-code-conversion("/home/alist/.config/emacs/straight/build-28.0.50/cider/cider-client.el" "/home/alist/.config/emacs/straight/build-28.0.50/cider/cider-client.el" nil t)
  require(cider-client)
  load-with-code-conversion("/home/alist/.config/emacs/straight/build-28.0.50/cider/cider.el" "/home/alist/.config/emacs/straight/build-28.0.50/cider/cider.el" nil t)
  command-execute(cider-jack-in record)
  execute-extended-command(nil "cider-jack-in" nil)
  funcall-interactively(execute-extended-command nil "cider-jack-in" nil)
  command-execute(execute-extended-command)
```

Because the `(require 'a)` call I've mentioned is still in `parseclj-parser.el`.

**Comment by sebastianpoeplau** [comment]
@plexus thanks for the quick reaction! I've just tried with 1.0.2 and it works for me :+1:
